#!/bin/bash

#Procedure taken from: http://grumbel.blogspot.de/2010/05/how-to-build-ubuntu-package.html

#prerequisites:
#sudo apt-get install dh-make git
#gpg --gen-key

#Compress the source archive to a tar distribution
#(Note: The folder should not contain a subfolder named like the project)
pushd ../limereg
git archive master --format=tar.gz --prefix=limereg-1.1.0/ . > ../limeregpkg/limereg-1.1.0.tar.gz
popd

#Import the tar distribution to a new git upstream folder
mkdir limereg
pushd limereg
git init
git-import-orig -u 1.1.0 ../limereg-1.1.0.tar.gz

#When executed for the first time the package description folder debian,
#which I decided to store in a file debian.tar.gz, has to be generated by:
#export EMAIL=rberg@berg-solutions.de
#dh_make -s -c bsd -p limereg_1.1.0 -f ../limereg-1.1.0.tar.gz
#Then modify the directories content as written in http://grumbel.blogspot.de/2010/05/how-to-build-ubuntu-package.html
#tar -czf ../debian.tar.gz debian/*

#When debian.tar.gz exists on subsequent runs, restore the debian folder created above
tar -xzf ../debian.tar.gz

echo Now adapt the files in the folder limereg/debian to the new version (e.g. version number)
echo Then execute:
echo cd limereg
echo git-buildpackage --git-ignore-new
echo .
echo Check the lint output for warnings and errors. Test the package by calling
echo apt-get install pbuilder
echo sudo pbuilder --create 
echo optional: sudo pbuilder update --components "main restricted universe multiverse" --override-config
echo sudo pbuilder --build limereg_1.1.0.dsc
echo ls /var/cache/pbuilder/results
echo .
echo Then publish on launchpad.net, create an account there
echo dput ppa:your_username/ppa package_version-1_source.changes
echo Test the repository
echo sudo add-apt-repository ppa:your_username/ppa
echo sudo apt-get update
echo sudo apt-get install limereg
