#!/bin/bash

#prerequisites:
#sudo apt-get install dh-make git
#gpg --gen-key

#Compress the source archive to a tar distribution
#(Note: The folder should not contain a subfolder named like the project)
pushd ../limereg
git archive master --format=tar.gz --prefix=limereg-1.1.0/ . > ../limeregpkg/limereg-1.1.0.tar.gz
popd

#Import the tar distribution to a new git upstream folder
mkdir limereg
pushd limereg
git init
git-import-orig -u 1.1.0 ../limereg-1.1.0.tar.gz

#When executed for the first time the package description folder debian,
#which I decided to store in a file debian.tar.gz, has to be generated by:
#export EMAIL=rberg@berg-solutions.de
#dh_make -s -c bsd -p limereg_1.1.0 -f ../limereg-1.1.0.tar.gz
#Then modify the directories content as written in http://grumbel.blogspot.de/2010/05/how-to-build-ubuntu-package.html
#tar -czf ../debian.tar.gz debian/*

#When debian.tar.gz exists on subsequent runs, restore the debian folder created above
tar -xzf ../debian.tar.gz

echo Now adapt the files in the folder limereg/debian to the new version (e.g. version number)
echo Then execute: cd limereg && git-buildpackage --git-ignore-new
